extends:
  - spectral:oas
  - spectral:asyncapi
  - spectral:arazzo
overrides:
  - files:
      # This is needed in the CLI, but it isn't used directly in the API
      - "openapi3*yaml#/components/schemas/v2DatasetRequest"
    rules:
      oas3-unused-component: "off"
  - files:
      - "openapi3*yaml"
    rules:
      no-$ref-siblings: "off"
